- task: DotNetCoreCLI@2
  displayName: Build project [% project %]
  inputs:
    projects: '[% project %]'
    arguments: /p:configuration="[% configuration %]" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageLocation="$(build.artifactstagingdirectory)\\[% configuration %]\\"  

